/**
 *
 *  Skills.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Skills.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::default_db;

const std::string Skills::Cols::_id = "id";
const std::string Skills::Cols::_skill_name = "skill_name";
const std::string Skills::primaryKeyName = "id";
const bool Skills::hasPrimaryKey = true;
const std::string Skills::tableName = "skills";

const std::vector<typename Skills::MetaData> Skills::metaData_ = {
    {"id", "int32_t", "int", 4, 1, 1, 1},
    {"skill_name", "std::string", "varchar(128)", 128, 0, 0, 1}};
const std::string &Skills::getColumnName(size_t index) noexcept(false) {
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Skills::Skills(const Row &r, const ssize_t indexOffset) noexcept {
    if (indexOffset < 0) {
        if (!r["id"].isNull()) {
            id_ = std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if (!r["skill_name"].isNull()) {
            skillName_ = std::make_shared<std::string>(
                r["skill_name"].as<std::string>());
        }
    } else {
        size_t offset = (size_t)indexOffset;
        if (offset + 2 > r.size()) {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull()) {
            id_ = std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if (!r[index].isNull()) {
            skillName_ =
                std::make_shared<std::string>(r[index].as<std::string>());
        }
    }
}

Skills::Skills(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 2) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() &&
        pJson.isMember(pMasqueradingVector[0])) {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int32_t>(
                (int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() &&
        pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            skillName_ = std::make_shared<std::string>(
                pJson[pMasqueradingVector[1]].asString());
        }
    }
}

Skills::Skills(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("skill_name")) {
        dirtyFlag_[1] = true;
        if (!pJson["skill_name"].isNull()) {
            skillName_ =
                std::make_shared<std::string>(pJson["skill_name"].asString());
        }
    }
}

void Skills::updateByMasqueradedJson(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 2) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() &&
        pJson.isMember(pMasqueradingVector[0])) {
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int32_t>(
                (int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() &&
        pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            skillName_ = std::make_shared<std::string>(
                pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void Skills::updateByJson(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("skill_name")) {
        dirtyFlag_[1] = true;
        if (!pJson["skill_name"].isNull()) {
            skillName_ =
                std::make_shared<std::string>(pJson["skill_name"].asString());
        }
    }
}

const int32_t &Skills::getValueOfId() const noexcept {
    static const int32_t defaultValue = int32_t();
    if (id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Skills::getId() const noexcept { return id_; }
void Skills::setId(const int32_t &pId) noexcept {
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Skills::PrimaryKeyType &Skills::getPrimaryKey() const {
    assert(id_);
    return *id_;
}

const std::string &Skills::getValueOfSkillName() const noexcept {
    static const std::string defaultValue = std::string();
    if (skillName_)
        return *skillName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Skills::getSkillName() const noexcept {
    return skillName_;
}
void Skills::setSkillName(const std::string &pSkillName) noexcept {
    skillName_ = std::make_shared<std::string>(pSkillName);
    dirtyFlag_[1] = true;
}
void Skills::setSkillName(std::string &&pSkillName) noexcept {
    skillName_ = std::make_shared<std::string>(std::move(pSkillName));
    dirtyFlag_[1] = true;
}

void Skills::updateId(const uint64_t id) {
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Skills::insertColumns() noexcept {
    static const std::vector<std::string> inCols = {"skill_name"};
    return inCols;
}

void Skills::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[1]) {
        if (getSkillName()) {
            binder << getValueOfSkillName();
        } else {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Skills::updateColumns() const {
    std::vector<std::string> ret;
    if (dirtyFlag_[1]) {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Skills::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[1]) {
        if (getSkillName()) {
            binder << getValueOfSkillName();
        } else {
            binder << nullptr;
        }
    }
}
Json::Value Skills::toJson() const {
    Json::Value ret;
    if (getId()) {
        ret["id"] = getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getSkillName()) {
        ret["skill_name"] = getValueOfSkillName();
    } else {
        ret["skill_name"] = Json::Value();
    }
    return ret;
}

Json::Value Skills::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const {
    Json::Value ret;
    if (pMasqueradingVector.size() == 2) {
        if (!pMasqueradingVector[0].empty()) {
            if (getId()) {
                ret[pMasqueradingVector[0]] = getValueOfId();
            } else {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (getSkillName()) {
                ret[pMasqueradingVector[1]] = getValueOfSkillName();
            } else {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId()) {
        ret["id"] = getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getSkillName()) {
        ret["skill_name"] = getValueOfSkillName();
    } else {
        ret["skill_name"] = Json::Value();
    }
    return ret;
}

bool Skills::validateJsonForCreation(const Json::Value &pJson,
                                     std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if (pJson.isMember("skill_name")) {
        if (!validJsonOfField(1, "skill_name", pJson["skill_name"], err, true))
            return false;
    } else {
        err = "The skill_name column cannot be null";
        return false;
    }
    return true;
}
bool Skills::validateMasqueradedJsonForCreation(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector, std::string &err) {
    if (pMasqueradingVector.size() != 2) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty()) {
            if (pJson.isMember(pMasqueradingVector[0])) {
                if (!validJsonOfField(0, pMasqueradingVector[0],
                                      pJson[pMasqueradingVector[0]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (pJson.isMember(pMasqueradingVector[1])) {
                if (!validJsonOfField(1, pMasqueradingVector[1],
                                      pJson[pMasqueradingVector[1]], err, true))
                    return false;
            } else {
                err =
                    "The " + pMasqueradingVector[1] + " column cannot be null";
                return false;
            }
        }
    } catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}
bool Skills::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    } else {
        err = "The value of primary key must be set in the json object for "
              "update";
        return false;
    }
    if (pJson.isMember("skill_name")) {
        if (!validJsonOfField(1, "skill_name", pJson["skill_name"], err, false))
            return false;
    }
    return true;
}
bool Skills::validateMasqueradedJsonForUpdate(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector, std::string &err) {
    if (pMasqueradingVector.size() != 2) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty() &&
            pJson.isMember(pMasqueradingVector[0])) {
            if (!validJsonOfField(0, pMasqueradingVector[0],
                                  pJson[pMasqueradingVector[0]], err, false))
                return false;
        } else {
            err = "The value of primary key must be set in the json object for "
                  "update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() &&
            pJson.isMember(pMasqueradingVector[1])) {
            if (!validJsonOfField(1, pMasqueradingVector[1],
                                  pJson[pMasqueradingVector[1]], err, false))
                return false;
        }
    } catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}
bool Skills::validJsonOfField(size_t index, const std::string &fieldName,
                              const Json::Value &pJson, std::string &err,
                              bool isForCreation) {
    switch (index) {
    case 0:
        if (pJson.isNull()) {
            err = "The " + fieldName + " column cannot be null";
            return false;
        }
        if (isForCreation) {
            err = "The automatic primary key cannot be set";
            return false;
        }
        if (!pJson.isInt()) {
            err = "Type error in the " + fieldName + " field";
            return false;
        }
        break;
    case 1:
        if (pJson.isNull()) {
            err = "The " + fieldName + " column cannot be null";
            return false;
        }
        if (!pJson.isString()) {
            err = "Type error in the " + fieldName + " field";
            return false;
        }
        if (pJson.isString() && std::strlen(pJson.asCString()) > 128) {
            err = "String length exceeds limit for the " + fieldName +
                  " field (the maximum value is 128)";
            return false;
        }

        break;
    default:
        err = "Internal error in the server";
        return false;
    }
    return true;
}
